plugins {
    id 'base'
    id 'net.minecraftforge.gradle' version '6.0.54' apply false
}

allprojects {
    group = 'com.dricetea.vh3patch'
    version = rootProject.mod_version
    repositories {
        mavenCentral()
        maven { url = 'https://maven.minecraftforge.net/' }
    }
}
subprojects {
    apply plugin: 'java'
    java.toolchain.languageVersion = JavaLanguageVersion.of(17)
    tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8' }
    tasks.withType(AbstractArchiveTask).configureEach {
        preserveFileTimestamps = false
        reproducibleFileOrder = true
    }
    tasks.withType(Test).configureEach { useJUnitPlatform() }
    dependencies { testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2' }
}

tasks.register('distribution', Sync) {
    dependsOn ':transformer:jar', ':runtime:reobfJar', ':transformer:verifyTarget', ':transformer:prepareVpConfig'
    into layout.buildDirectory.dir('distribution')
    from(project(':transformer').tasks.named('jar'))
    from(project(':runtime').tasks.named('jar'))
    from(project(':transformer').layout.buildDirectory.dir('compat')) { into 'compat' }
}
tasks.named('check') { dependsOn ':transformer:check', ':runtime:check', ':transformer:verifyTarget' }
tasks.named('build') { dependsOn ':transformer:build', ':runtime:build', 'distribution' }
