; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Minecraft Modpack Vault Hunters 3rd Edition 汉化"
#define MyAppPublisher "VM-Chinese-translate-group"
#define MyAppURL "https://vmct-cn.top/modpacks/vault/"   
#define ModPackVersion "3.21.7"
#define MyAppVersion "2.6.18"
#define ExpectedMD5 "c29b0e77ba86c8a2ca2679c416e9bcb3"
#define ModFileName "3.21.6.6884"

#define OriPackUrl "https://mediafilez.forgecdn.net/files/8527/845/Vault%20Hunters%20Third%20Edition-3.21.7.zip"
#define VpDlUrl 'https://mediafilez.forgecdn.net/files/6482/746/vaultpatcher-all-1.4.4%2B3.jar'
#define VpDlName 'vaultpatcher-all-1.4.4+3.jar'
#define I18nDlUrl 'https://mediafilez.forgecdn.net/files/7173/159/I18nUpdateMod-3.7.0-all.jar'
#define I18nDlName 'I18nUpdateMod-3.7.0-all.jar'
#define VmctDlUrl 'https://mediafilez.forgecdn.net/files/6891/488/VMTranslationUpdate-forge-4.0.0%2Bmc1.18.2.jar'
#define VmctDlName 'VMTranslationUpdate-forge-4.0.0+mc1.18.2.jar'
#define JechDlUrl 'https://mediafilez.forgecdn.net/files/4259/230/jecharacters-1.18.2-4.3.11.jar'
#define JechDlName 'jecharacters-1.18.2-4.3.11.jar'
#define OculusDlUrl 'https://mediafilez.forgecdn.net/files/4578/744/oculus-mc1.18.2-1.6.4.jar'
#define OculusDlName 'oculus-mc1.18.2-1.6.4.jar'
      
[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{5670F72E-CF41-4475-A008-50DBCD145F6C}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}                                                                                                                                                        
AppUpdatesURL={#MyAppURL}
DefaultDirName={src} 
UsePreviousAppDir=no
DisableDirPage=no
AppendDefaultDirName=no
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
Uninstallable=no
VersionInfoVersion={#MyAppVersion}                                                
VersionInfoCopyright={#MyAppPublisher}
VersionInfoDescription=宝藏猎人3rd_汉化安装包
LicenseFile=LICENSE.txt
InfoBeforeFile=Inno setup before.txt
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=..\..\[发布文件]\宝藏猎人3rd-汉化打包-{#ModPackVersion}-VM汉化组-V{#MyAppVersion}
OutputBaseFilename=VM汉化组_宝藏猎人3rd汉化安装_{#ModPackVersion}_V{#MyAppVersion}
SetupIconFile=pack.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"

[Types]
Name: xz; Description:"汉化安装搭配"; Flags: iscustom     

[Components]
Name: basic; Description: "基础+硬编码汉化" ; Types: xz ; Flags: fixed
Name: enhance; Description: "游戏体验增强 [推荐]" ; Types: xz
Name: auxiliary; Description: "辅助配置：最低画质+Jade启用" 
Name: smallthings; Description: "支持阿鹉谢谢喵 [适配PCL]"
Name: vp; Description: "模组快捷下载：硬编码汉化[VaultPatcher] [必装，双端]"; Types: xz ; ExtraDiskSpaceRequired: 164715
Name: i18n; Description: "模组快捷下载：I18n自动汉化更新 [必装，客户端]"; Types: xz ;  ExtraDiskSpaceRequired: 49726
Name: vmct; Description: "模组快捷下载：整合包汉化更新检测 [选装，客户端]"; Types: xz ; ExtraDiskSpaceRequired: 208794
Name: jech; Description: "模组快捷下载：JECh通用拼音搜索 [选装，客户端]"; ExtraDiskSpaceRequired: 282877
Name: ocu; Description: "模组快捷下载：Oculus（启用光影） [选装，客户端]"; ExtraDiskSpaceRequired: 3503276

[Files]
Source: "基础+硬编码汉化\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs ; Components: basic;
Source: "游戏体验增强\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs ; Components: enhance;
Source: "辅助配置\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs ; Components: auxiliary;
Source: "支持阿鹉谢谢喵\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs ; Components: smallthings;
Source: "{tmp}\{#VpDlName}"; DestDir: "{app}\mods\"; Flags: external ; Components: vp;
Source: "{tmp}\{#I18nDlName}"; DestDir: "{app}\mods\"; Flags: external ; Components: i18n;
Source: "{tmp}\{#VmctDlName}"; DestDir: "{app}\mods\"; Flags: external ; Components: vmct;
Source: "{tmp}\{#JechDlName}"; DestDir: "{app}\mods\"; Flags: external ; Components: jech;
Source: "{tmp}\{#OculusDlName}"; DestDir: "{app}\mods\"; Flags: external ; Components: ocu;
Source: "..\..\必要文件\iss-plugin-7z\*"; DestDir: "{tmp}\7z"; Flags: ignoreversion ; Components: basic;

[InstallDelete]
; Remove only previous VTP installation JARs before installing the single bundle.
Type: files; Name: "{app}\mods\vh3_translation_patch-1.*.jar"; Components: basic
Type: files; Name: "{app}\mods\vh3_translation_patch-transformer-1.*.jar"; Components: basic

[Run]
Filename: "{cmd}"; Parameters: "/c start https://www.bilibili.com/read/cv25168950/"; Flags: shellexec postinstall unchecked ; Description: "前往汉化专栏点赞投币！"

[Code]
var
  InstallModePage: TInputOptionWizardPage;
  DownloadPage: TDownloadWizardPage;
  FileName1: String;
  DestPath1: String;
  Url,DLmodpack: String;
  NextButtonClicked :Boolean;

function OnDownloadProgress(const Url, FileName: String; const Progress, ProgressMax: Int64): Boolean;
begin
  if Progress = ProgressMax then
    Log(Format('成功下载文件到'+ExpandConstant('{tmp}')+'\ %s', [FileName]));
  Result := True;
end;

procedure InitializeWizard;
begin
  InstallModePage := CreateInputOptionPage(wpWelcome,'选择安装模式', '选择安装汉化补丁会正常将汉化包安装到整合包根目录；选择导入包会下载原版整合包的导入包，并注入汉化内容，生成新的启动器导入包','请选择安装模式：', True, False);
  InstallModePage.Add('安装汉化补丁（默认）');
  InstallModePage.Add('生成汉化后的整合包导入包');
  DownloadPage := CreateDownloadPage(SetupMessage(msgWizardPreparing), SetupMessage(msgPreparingDesc), @OnDownloadProgress);
end;

function RobustDownload(
  Url, BaseName, RequiredSHA256OfFile: String): Boolean;
var
  Retry: Boolean;
  Answer: Integer;
begin
  repeat
    try
      DownloadPage.Clear;
      DownloadPage.Add(Url, BaseName, RequiredSHA256OfFile);
      DownloadPage.Download;
      Retry := False;
      Result := True;
    except
      if DownloadPage.AbortedByUser then
      begin
        Log('用户取消了下载操作')
        Result := False;
        Retry := False;
      end
        else
      begin
        DownloadPage.Msg2Label.Caption := Url;
        Answer :=
          SuppressibleMsgBox(
            AddPeriod(GetExceptionMessage),
            mbCriticalError, MB_ABORTRETRYIGNORE, IDABORT);
        Retry := (Answer = IDRETRY);
        Result := (Answer <> IDABORT);
      end;
    end;
  until not Retry;
end;
function NextButtonClick(CurPageID: Integer): Boolean;
var
  ResultCode: Integer;
  a: Boolean;
begin
  a := True;
 try
  if CurPageID = wpReady then begin
    try
      DownloadPage := CreateDownloadPage(SetupMessage(msgWizardPreparing), SetupMessage(msgPreparingDesc), @OnDownloadProgress);
      DownloadPage.Show;
      if DLmodpack = 'True' then
        a := a and RobustDownload('{#OriPackUrl}', 'Vault Hunters 3rd Edition.zip', '');
        CreateDir(ExpandConstant('{tmp}\Vault Hunters 3rd Edition-{#ModPackVersion}-内置汉化导入包-VM汉化组-V{#MyAppVersion}'));
        if Exec('cmd.exe', '/C tar -xf "' + ExpandConstant('{tmp}\Vault Hunters 3rd Edition.zip') + '" -C "' + ExpandConstant('{tmp}\Vault Hunters 3rd Edition-{#ModPackVersion}-内置汉化导入包-VM汉化组-V{#MyAppVersion}') + '"', '', SW_HIDE, ewWaitUntilTerminated, ResultCode) then begin
          if not ResultCode = 0 then begin
            MsgBox('解压原版整合包导入包失败，可能是因为没有权限，请选择另一个安装模式，错误代码: ' + IntToStr(ResultCode), mbError, MB_OK);
            MsgBox('Command:'+'/C tar -xf "' + ExpandConstant('{tmp}\Vault Hunters 3rd Edition.zip') + '" -C "' + ExpandConstant('{tmp}\Vault Hunters 3rd Edition-{#ModPackVersion}-内置汉化导入包-VM汉化组-V{#MyAppVersion}') + '"', mbInformation, MB_OK)
          end;
        end;     
      if IsComponentSelected('vp') then
        a := a and RobustDownload('{#VpDlUrl}', '{#VpDlName}', '');
      if IsComponentSelected('i18n') then
        a := a and RobustDownload('{#I18nDlUrl}', '{#I18nDlName}', '');
      if IsComponentSelected('vmct') then
        a := a and RobustDownload('{#VmctDlUrl}', '{#VmctDlName}', '');
      if IsComponentSelected('jech') then
        a := a and RobustDownload('{#JechDlUrl}', '{#JechDlName}', '');
      if IsComponentSelected('ocu') then
        a := a and RobustDownload('{#OculusDlUrl}', '{#OculusDlName}', '');
      
      Result := a; 
    finally
      DownloadPage.Hide;
    end;
  end
    else Result := True;
 finally
  NextButtonClicked := True;
 end;
end;

function GetMD5OfFile(FileName: String): AnsiString;
var
  ResultCode: Integer;
  OutputString: AnsiString;
  TmpFile: String;
begin
  if not FileExists(FileName) then
  begin
    // MsgBox('安装目录中未找到目标文件，安装目录可能不是对应版本的宝藏猎人整合包！', mbError, MB_OK);
    Result := '';
    Exit;
  end;
  TmpFile := ExpandConstant('{tmp}') + '\md5.tmp';
  if not Exec('cmd.exe', '/C certutil -hashfile "' + FileName + '" MD5 > "' + TmpFile + '"', '', SW_HIDE, ewWaitUntilTerminated, ResultCode) then
  begin
    MsgBox('无法执行certutil.exe，可能是没有权限', mbError, MB_OK);
    Result := '';
    Exit;
  end;

  if not LoadStringFromFile(TmpFile, OutputString) then
  begin
    MsgBox('无法加载certutil.exe的输出', mbError, MB_OK);
    Result := '';
    Exit;
  end;
  DelTree(ExpandConstant('{app}\vaultpatcher'), True, True, True);
  DeleteFile(ExpandConstant('{app}\mods\I18nUpdateMod-3.6.0-all.jar'));
  DeleteFile(ExpandConstant('{app}\mods\VMTranslationUpdate-forge-3.1.0+mc1.18.2.jar'));
  DeleteFile(ExpandConstant('{app}\mods\vaultpatcher-all-1.4.2+2.jar'));
  DeleteFile(ExpandConstant('{app}\mods\vaultpatcher-all-1.5.0.jar'));
  DeleteFile(ExpandConstant('{app}\mods\vaultpatcher-all-1.5.2.jar'));
  DeleteFile(ExpandConstant('{app}\mods\vaultpatcher-all-1.5.3-hotfix.jar'));
  Result := Copy(OutputString, Pos(#13#10, OutputString) + 2, Pos(#13#10, Copy(OutputString, Pos(#13#10, OutputString) + 2, Length(OutputString))) - 1);
end;

procedure CurPageChanged(CurPageID: Integer);
var
  ModFolder: string;
  ExpectedMD5Rewrite: AnsiString;
  ActualMD5: AnsiString;
begin
  if (CurPageID = wpSelectDir) then begin
    if InstallModePage.SelectedValueIndex = 1 then begin
      WizardForm.DirEdit.Text := ExpandConstant('{tmp}\Vault Hunters 3rd Edition-{#ModPackVersion}-内置汉化导入包-VM汉化组-V{#MyAppVersion}\overrides');
      DLmodpack := 'True';
      WizardForm.DirEdit.Enabled := False;
      WizardForm.DirBrowseButton.Enabled := False;
    end else begin
      DLmodpack := 'False';
      WizardForm.DirEdit.Enabled := True;
      WizardForm.DirBrowseButton.Enabled := True;
    end;
  end;
  if DLmodpack = 'False' then begin
    ModFolder := '{app}\mods\the_vault-1.18.2-{#ModFileName}.jar';
    ExpectedMD5Rewrite := '{#ExpectedMD5}';
    if (CurPageID = wpSelectComponents) then begin
      ActualMD5 := GetMD5OfFile (ExpandConstant(ModFolder));
      if not CompareText(ExpectedMD5Rewrite, ActualMD5) = 0 then begin
        MsgBox('检测到核心模组文件版本有误，此汉化包可能不兼容当前整合包版本，或安装路径错误。请再次核对。', mbError, MB_OK);
        MsgBox('检测到核心模组文件版本有误，此汉化包可能不兼容当前整合包版本，或安装路径错误。请再次核对。', mbError, MB_OK);
        MsgBox('检测到核心模组文件版本有误！此汉化包可能不兼容当前整合包版本，或安装路径错误！请再次核对！', mbError, MB_OK);
        MsgBox('检测到核心模组文件版本有误！此汉化包可能不兼容当前整合包版本，或安装路径错误！请再次核对！', mbError, MB_OK);
        MsgBox('检测到核心模组文件版本有误！此汉化包可能不兼容当前整合包版本，或安装路径错误！请再次核对！再次点击以强制安装。', mbError, MB_OK);
      end;
      if ExpectedMD5Rewrite <> ActualMD5 then begin
        MsgBox('检测到核心模组文件版本有误，此汉化包可能不兼容当前整合包版本，或安装路径错误。请再次核对。', mbError, MB_OK);
        MsgBox('检测到核心模组文件版本有误，此汉化包可能不兼容当前整合包版本，或安装路径错误。请再次核对。', mbError, MB_OK);
        MsgBox('检测到核心模组文件版本有误！此汉化包可能不兼容当前整合包版本，或安装路径错误。请再次核对！', mbError, MB_OK);
        MsgBox('检测到核心模组文件版本有误！此汉化包可能不兼容当前整合包版本，或安装路径错误。请再次核对！', mbError, MB_OK);
        MsgBox('检测到核心模组文件版本有误！此汉化包可能不兼容当前整合包版本，或安装路径错误。请再次核对！再次点击以强制安装。', mbError, MB_OK);
      end;
    end;
  end;
  if (CurPageID = wpReady) and not NextButtonClicked then begin
    NextButtonClick(CurPageID);
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  ResultCode ,ErrorCode: Integer;
  Command2: string;
begin
  if CurStep = ssPostInstall then begin
    if DLmodpack = 'True' then begin
      WizardForm.StatusLabel.Caption := '正在重打包整合包导入包，请稍候...';
      Command2 := 'a -tzip "' + ExtractFileDir(ExpandConstant('{srcexe}')) + '\Vault Hunters 3rd Edition-{#ModPackVersion}-内置汉化导入包-VM汉化组-V{#MyAppVersion}.zip" "' + ExpandConstant('{tmp}\Vault Hunters 3rd Edition-{#ModPackVersion}-内置汉化导入包-VM汉化组-V{#MyAppVersion}') + '\*"';
      if Exec(ExpandConstant('{tmp}\7z\7z.exe'), Command2,'', SW_HIDE, ewWaitUntilTerminated, ResultCode) then begin
        if ResultCode = 0 then begin
          WizardForm.StatusLabel.Caption := '重打包完成。';
          MsgBox('重打包整合包导入包完成，拖入启动器安装后直接启动，点击确定打开目录，存放目录: ' + ExtractFileDir(ExpandConstant('{srcexe}')), mbInformation, MB_OK);
          ShellExec('', 'explorer.exe', ExtractFileDir(ExpandConstant('{srcexe}')), '', SW_SHOWNORMAL, ewNoWait, ErrorCode);
        end else begin
          WizardForm.StatusLabel.Caption := '重打包失败。';
          MsgBox('重打包整合包导入包失败，请尝试其他汉化安装模式，错误代码: ' + IntToStr(ResultCode), mbError, MB_OK);
          MsgBox('Command:'+Command2, mbInformation, MB_OK)
        end
      end else begin
        WizardForm.StatusLabel.Caption := '重打包失败。';
        MsgBox('重打包整合包导入包失败，没能调用压缩组件，请尝试其他汉化安装模式', mbError, MB_OK);
        MsgBox('Command:'+Command2, mbInformation, MB_OK)
      end;
    end;
  end;
end;